name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22  # 使用您当前支持的Go版本
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o zbp-niuniu-sql-linux main.go
          GOOS=windows GOARCH=amd64 go build -o zbp-niuniu-sql-windows main.go
          GOOS=darwin GOARCH=amd64 go build -o zbp-niuniu-sql-macos main.go
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: zbp-niuniu-sql-*
